spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ord_migration
    username: ord_user
    password: ord_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    show-sql: true
